debug: fandango not found

diff --git a/.github/workflows/deploy-book.yml b/.github/workflows/deploy-book.yml
--- a/.github/workflows/deploy-book.yml
+++ b/.github/workflows/deploy-book.yml
@@ -30,6 +30,10 @@ jobs:
       run: |
         pip install fandango-fuzzer jupyter-book pyppeteer ghp-import black
 
+    - name: Locate Fandango
+      run: |
+        which fandango || echo "Fandango not found in PATH"
+
     # Build the book
     - name: Build the book
       run: |
